services:
  web:
    build:
      context: .
    environment:
      DB_URL: mongodb://app:pass@db/fdc_dev?authSource=admin
    ports:
    - "3000:3000"
    volumes:
    - /app/.next/
    - /app/node_modules/
    - ./:/app/:cached

  db:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
    - "27017:27017"
    volumes:
    - db:/data/db/
volumes:
  db:
